In [2]:
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.patches as mpatches
import numpy as np
import pandas as pd
import cvxpy as cp
from scipy.stats import poisson, uniform, expon, pareto
from scipy.optimize import minimize, fsolve
import scipy.optimize as opt
import scipy.integrate as integrate
from tqdm import tqdm
from mdptoolbox import mdp, util
import itertools
from scipy.sparse import csr_matrix, lil_matrix
from matplotlib.patches import Patch
import math
import random
import sympy as sp
from sympy.printing.latex import print_latex
from scipy.optimize import least_squares

# tullock

In [67]:
n = 2

In [68]:
bs = [sp.Symbol('b{}'.format(i), positive=True, real=True) for i in range(n)]
vs = [sp.Symbol('v{}'.format(i), positive=True, real=True) for i in range(n)]

den = sum(bs)
xs  = [b/den for b in bs]
us  = [xs[i]*vs[i] - bs[i] for i in range(n)] 

In [69]:
us[0]

b0*v0/(b0 + b1) - b0

In [70]:
focs = [sp.Eq(sp.diff(us[i], bs[i]),0) for i in range(n)]
focs[0]

Eq(-b0*v0/(b0 + b1)**2 + v0/(b0 + b1) - 1, 0)

In [71]:
focs[1]

Eq(-b1*v1/(b0 + b1)**2 + v1/(b0 + b1) - 1, 0)

In [72]:
solutions = sp.solve(focs, bs, dict=True)

In [73]:
solutions[0]

{b0: v0*v1*(v0**2 + 2*v0*v1 + v1**2 - v1*sqrt(v0**2 + 2*v0*v1 + v1**2))/(v0**2 + 2*v0*v1 + v1**2)**(3/2),
 b1: v0*v1**2/(v0**2 + 2*v0*v1 + v1**2)}

In [75]:
xhat = [x.subs(solutions[0]) for x in xs]
sp.simplify(xhat[1])

v1/sqrt(v0**2 + 2*v0*v1 + v1**2)

$$
    x_0 = \frac{v_0}{v_0+v_1}, \quad x_1 = \frac{v_1}{v_0+v_1}
$$

In [83]:
[xhat[i].subs({vs[0]: 3, vs[1]: 4}) for i in range(n)]

[3/7, 4/7]

In [64]:
values = [2, 2.2, 2.4, 2.6, 2.8, 3., 3.2][2:]
n      = len(values)

def U_i(x, i):
    return values[i] * x

def U_tilde(x):
    """
    Compute the total modified utility:
      sum_i [(1-x_i)*U_i(x_i) + \int_0^{x_i} U_i(y) dy]
    where x is a vector of allocations.
    """
    total = 0
    for i in range(n):
        xi = x[i]
        term1 = (1 - xi) * U_i(xi, i)
        term2, err = integrate.quad(lambda y: U_i(y, i), 0, xi)
        total += term1 + term2
    return total

def objective(x):
    return -U_tilde(x)

constraints = [{'type': 'eq', 'fun': lambda x: np.sum(x) - 1}]
bounds = [(0, 1) for _ in range(n)]
x0 = np.array([1.0/n] * n)

result = opt.minimize(objective, x0, bounds=bounds, constraints=constraints)

In [65]:
# Print the results.
print("Optimal allocations:", result.x)
print("Maximized total modified utility:", -result.fun)

Optimal allocations: [0.07626306 0.14726937 0.20832284 0.26093279 0.30721193]
Maximized total modified utility: 2.5660448922687253


In [61]:
def equilTheo(vs):
    n = len(vs)
    total = sum(1/vs)
    return 1 - (n-1)/(vs*total)

In [63]:
equilTheo(np.array(values[2:]))

array([0.07625936, 0.14731633, 0.20822231, 0.26100749, 0.30719452])

In [43]:
equilTheo(np.array(values[1:]))

array([-0.17647059,  0.11764706,  0.41176471,  0.64705882])

In [44]:
equilTheo(np.array(values[2:]))

array([0.03225806, 0.35483871, 0.61290323])

In [103]:
U_i(result.x[0], 0), U_i(result.x[1], 1)

(0.022332493782350967, 397.0223341623532)